version: '3'

volumes:
    database_data:
        driver: local

services:
    database:
        image: postgres:latest
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        expose:
            - 5432
        volumes:
            - ./docker/initdb:/docker-entrypoint-initdb.d
            - database_data:/var/lib/postgresql/data
        networks:
            - multitech
        restart: always

    application:
        build: ./docker/multitech_web
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        expose:
            - 8000
        volumes:
           - ./multitech_web:/opt/app
        networks:
            - multitech
        depends_on:
            - database
        restart: always

    nginx:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/logs/nginx:/var/log/nginx:rw
            - ./multitech_web:/opt/app:ro
        networks:
            - multitech
        depends_on:
            - application

networks:
    multitech:
        driver: bridge
