version: '3'

services:
    application:
        build: ./docker/multitech_web
        entrypoint: /usr/local/bin/python
        command: manage.py runserver 0.0.0.0:8000
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        expose:
            - 8000
        volumes:
            - ./multitech_web:/opt/app
        networks:
            - multitech
        depends_on:
            - database
        restart: always
