# Generated by Django 2.0.4 on 2018-06-20 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20180620_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_categorys',
            new_name='sub_categories',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Category'),
        ),
    ]
