# Generated by Django 2.0.4 on 2018-06-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20180620_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_categories',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='products',
        ),
    ]
