# Generated by Django 2.0.4 on 2018-07-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='shit',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='ssss',
        ),
    ]
